import 'package:flutter/material.dart';
import 'package:mobile/model/buy.dart';

List<Buy> buys = [
  Buy(id: '1', title: 'Introduction to Computer Science', owner: 'malek', description: 'This course introduces students to the basic concepts of computer science. It covers the basic programming concepts, data structures, and algorithms, and introduces students to the software development process. Students will learn to use a programming language, and to write algorithms in a programming language. This course is a prerequisite for the CS program.', image: Image.asset('images/image_1.jpg'), size: 100, room_number: 5, location: 'bizerte', price: 100055),
  Buy(id: '2', title: 'Introduction to Computer Science', owner: 'malek', description: 'This course introduces students to the basic concepts of computer science. It covers the basic programming concepts, data structures, and algorithms, and introduces students to the software development process. Students will learn to use a programming language, and to write algorithms in a programming language. This course is a prerequisite for the CS program.', image: Image.asset('images/image_2.jpg'), size: 100, room_number: 5, location: 'bizerte', price: 5044599),
  Buy(id: '3', title: 'Introduction to Computer Science', owner: 'malek', description: 'This course introduces students to the basic concepts of computer science. It covers the basic programming concepts, data structures, and algorithms, and introduces students to the software development process. Students will learn to use a programming language, and to write algorithms in a programming language. This course is a prerequisite for the CS program.', image: Image.asset('images/image_3.jpg'), size: 100, room_number: 5, location: 'bizerte', price: 444499),
  Buy(id: '4', title: 'Introduction to Computer Science', owner: 'malek', description: 'This course introduces students to the basic concepts of computer science. It covers the basic programming concepts, data structures, and algorithms, and introduces students to the software development process. Students will learn to use a programming language, and to write algorithms in a programming language. This course is a prerequisite for the CS program.', image: Image.asset('images/image_4.jpg'), size: 100, room_number: 5, location: 'bizerte', price: 45.99),
  Buy(id: '5', title: 'Introduction to Computer Science', owner: 'malek', description: 'This course introduces students to the basic concepts of computer science. It covers the basic programming concepts, data structures, and algorithms, and introduces students to the software development process. Students will learn to use a programming language, and to write algorithms in a programming language. This course is a prerequisite for the CS program.', image: Image.asset('images/image_5.jpg'), size: 100, room_number: 5, location: 'bizerte', price: 100.95),
  Buy(id: '6', title: 'Introduction to Computer Science', owner: 'malek', description: 'This course introduces students to the basic concepts of computer science. It covers the basic programming concepts, data structures, and algorithms, and introduces students to the software development process. Students will learn to use a programming language, and to write algorithms in a programming language. This course is a prerequisite for the CS program.', image: Image.asset('images/image_6.jpg'), size: 100, room_number: 5, location: 'bizerte', price: 120.10),
  Buy(id: '7', title: 'Introduction to Computer Science', owner: 'malek', description: 'This course introduces students to the basic concepts of computer science. It covers the basic programming concepts, data structures, and algorithms, and introduces students to the software development process. Students will learn to use a programming language, and to write algorithms in a programming language. This course is a prerequisite for the CS program.', image: Image.asset('images/image_7.jpg'), size: 100, room_number: 5, location: 'bizerte', price: 100.99),
  Buy(id: '8', title: 'Introduction to Computer Science', owner: 'malek', description: 'This course introduces students to the basic concepts of computer science. It covers the basic programming concepts, data structures, and algorithms, and introduces students to the software development process. Students will learn to use a programming language, and to write algorithms in a programming language. This course is a prerequisite for the CS program.', image: Image.asset('images/image_8.jpg'), size: 100, room_number: 5, location: 'bizerte', price: 50.99),
  Buy(id: '9', title: 'Introduction to Computer Science', owner: 'malek', description: 'This course introduces students to the basic concepts of computer science. It covers the basic programming concepts, data structures, and algorithms, and introduces students to the software development process. Students will learn to use a programming language, and to write algorithms in a programming language. This course is a prerequisite for the CS program.', image: Image.asset('images/image_1.jpg'), size: 100, room_number: 5, location: 'bizerte', price: 150.99),
  Buy(id: '10', title: 'Introduction to Computer Science', owner: 'malek', description: 'This course introduces students to the basic concepts of computer science. It covers the basic programming concepts, data structures, and algorithms, and introduces students to the software development process. Students will learn to use a programming language, and to write algorithms in a programming language. This course is a prerequisite for the CS program.', image: Image.asset('images/image_4.jpg'), size: 100, room_number: 5, location: 'bizerte', price: 45.99),
  Buy(id: '11', title: 'Introduction to Computer Science', owner: 'malek', description: 'This course introduces students to the basic concepts of computer science. It covers the basic programming concepts, data structures, and algorithms, and introduces students to the software development process. Students will learn to use a programming language, and to write algorithms in a programming language. This course is a prerequisite for the CS program.', image: Image.asset('images/image_5.jpg'), size: 100, room_number: 5, location: 'bizerte', price: 100.95),
  Buy(id: '12', title: 'Introduction to Computer Science', owner: 'malek', description: 'This course introduces students to the basic concepts of computer science. It covers the basic programming concepts, data structures, and algorithms, and introduces students to the software development process. Students will learn to use a programming language, and to write algorithms in a programming language. This course is a prerequisite for the CS program.', image: Image.asset('images/image_2.jpg'), size: 100, room_number: 5, location: 'bizerte', price: 120.10),
];